kobosil_time_warp = [
    "No Neim Lost In The Dark", 
    "Svetec, Sikztah - Phoenix (Original Mix)",
    "Forbidden Out of Order",
    "SuturaThe Reaper (O.B.I Remix)", 
    "bastet - Disaster Rave",
    "Minor Dott - OUTSTANDING (unreleased)",
    "Geck-o - Go Higher Go Faster (Original Mix)",
    "Vizionn - Control (Original Mix)",
    "Bastet - Witching Hill (Original Mix)",
    "Matthew & Arkus - P.Life in Cube",
    "Nobody - Eat Shit and Schranz (Revisit)",
    "PETDuo - Hyped Demons (Andreas Kraemer RMX)",
    "Crime, Gyko Killa - Killa",
    "Ben Techy - On The Dance Floor",
    "Luciid - Vault",
]